name: Update Ookla Data

on:
  schedule:
    - cron: '0 0 1 */3 *' 
  workflow_dispatch: 

# ეს ნაწილი აუცილებელია, რომ სკრიპტმა შეძლოს მონაცემების შენახვა (push)
permissions:
  contents: write 

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      # აქ განვაახლეთ ვერსიები v4 და v5-ზე
      - uses: actions/checkout@v4 
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install geopandas pyarrow requests
      - name: Run script
        run: python fetch_ookla.py
      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/
          git commit -m "Auto-update Georgia Ookla data" || exit 0
          git push
